### PR TITLE
Add infra-nw support

### PR DESCRIPTION
**Pull request by pkeerthana**
Add infra-nw support to allow ceph traffic to be sent via OVS internal port.

### CODE REVIEW

**Comment by jainvipin** [comment]
ping @erikh @mapuri @shaleman 
I wonder if we should define a new infra-nw object that includes standard network object and defines things on top. Including the new fields are totally redundant for user defined networks. How is inheritance equivalent is best done in Go?

**Comment by pkeerthana** [comment]
Looks like you embed the base type in a new struct to do inheritence in go: 
http://golangtutorials.blogspot.in/2011/06/inheritance-and-subclassing-in-go-or.html
Will check if it is possible for infra-nw..

**Comment by erikh** [comment]
we should be able to encapsulate this with a type that acts as a tuple of both values, which is the ideal way to do this .

**Comment by jainvipin** [comment]
@pkeerthana - had a chat with @shaleman; let's do following:
- move 'bool' to 'string' so we can create different type of networks; where type has semantics associated with it. The type you can use could be "infra"
- remove the InfraNwPort field from network config; let's name the port to be the network name itself so we don't have a confusion about things

**Comment by pkeerthana** [comment]
@jainvipin - sure, will do this. Thanks.

**Comment by shaleman** [comment]
LGTM

**Pull request merged**
